package optim_storage_infrastructure;

import org.cloudbus.cloudsim.UtilizationModelStochastic;

public class IoUtilizationModelStochasticWithStorage extends UtilizationModelStochastic {
	
	/** The CPU utilization generated by IO execution */
	private double ioCpuUtilization;
	
	public IoUtilizationModelStochasticWithStorage(long seed){
		super(seed);
		setIoCpuUtilization(0);
	}

	
	@Override
	public double getUtilization(double time) {
		if (getHistory().containsKey(time)) {
			return getHistory().get(time);
		}

		double utilization = getRandomGenerator().nextDouble();
		utilization += getIoCpuUtilization();
		getHistory().put(time, utilization);
		return utilization;
	}  
	
	public double getIoCpuUtilization() {
		return ioCpuUtilization;
	}

	public void setIoCpuUtilization(double ioCpuUtilization) {
		this.ioCpuUtilization = ioCpuUtilization;
	}
}
